// <auto-generated />
using Construction_Admin_Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Construction_Admin_Service.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230306070344_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Construction_Admin_Service.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experience");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "Warehouse associate"
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Assistant counselor"
                        },
                        new
                        {
                            Id = 3,
                            Detail = "Accountant"
                        },
                        new
                        {
                            Id = 4,
                            Detail = "HR"
                        },
                        new
                        {
                            Id = 5,
                            Detail = "Business Analyst"
                        },
                        new
                        {
                            Id = 6,
                            Detail = "Document Controller"
                        },
                        new
                        {
                            Id = 7,
                            Detail = "Software Developer"
                        },
                        new
                        {
                            Id = 8,
                            Detail = "Other"
                        });
                });

            modelBuilder.Entity("Construction_Admin_Service.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nationality_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nationality_Name = "Emirati"
                        },
                        new
                        {
                            Id = 2,
                            Nationality_Name = "Egyptian"
                        },
                        new
                        {
                            Id = 3,
                            Nationality_Name = "Iranian"
                        },
                        new
                        {
                            Id = 4,
                            Nationality_Name = "Pakistani"
                        },
                        new
                        {
                            Id = 5,
                            Nationality_Name = "Jordanian"
                        },
                        new
                        {
                            Id = 6,
                            Nationality_Name = "Kuwaiti"
                        },
                        new
                        {
                            Id = 7,
                            Nationality_Name = "Libyan"
                        },
                        new
                        {
                            Id = 8,
                            Nationality_Name = "Indian"
                        });
                });

            modelBuilder.Entity("Construction_Admin_Service.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("user");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
